#! /bin/sh

# This script is in the Public Domain, and comes with NO WARRANTY OF ANY KIND.

[ $# -eq 2 ] || {
    echo "Usage: $0 REST-HOST OUTPUT-DIRECTORY" >&2
    echo "Example: $0 localhost:8091 /tmp/mbinfo" >&2
    exit 1
}

a_node=shift
output_dir=shift

output_dir=$output_dir/info-`date +%Y-%m-%d`
echo "Saving mbcollect_info in '$output_dir'"

hosts=`curl -s http://"$a_node"/pools/default | python26 -mjson.tool | grep hostname | cut -d\" -f4 | cut -d: -f1`
echo "Current cluster hosts: `echo $hosts | xargs`"

mkdir -p "$output_dir"

cat <<EOF
Collection about to commence; expect a jumble of output as this is run in
parallel on all hosts.
EOF
sleep 3;

for h in $hosts; do
    # Turn "whatever-membase12.myhost.com" into "mb12"
    # TODO How to assume way less about host names?
    short=`echo $h | sed 's/^.*membase/mb/; s/[^0-9]*$//'`

    # Run in the background, so they all go in parallel
    # TODO `mktemp` works on Linux, but isn't terribly portable across various *nix
    ssh $h \
        'f=`mktemp`; /opt/membase/bin/mbcollect_info -v $f && cat $f && rm $f' \
        > "$output_dir/$short.zip" &
done

wait

echo "Done - $output_dir:"
ls -lh "$output_dir"

# vim:set ft=sh sw=4 et ai:
