#! /bin/sh

# This script is in the Public Domain, and comes with NO WARRANTY OF ANY KIND.

[ $# -eq 2 ] || {
    echo "Usage: $0 REST-HOST OUTPUT-DIRECTORY" >&2
    echo "Example: $0 localhost:8091 /tmp/mbinfo" >&2
    exit 1
}

a_node=$1; shift
output_dir=$1; shift

output_dir=$output_dir/info-`date +%Y-%m-%d`
echo "Saving mbcollect_info in '$output_dir'"

hosts=`curl -s http://"$a_node"/pools/default | python26 -mjson.tool | grep hostname | cut -d\" -f4 | cut -d: -f1`
echo "Current cluster hosts: `echo $hosts | xargs`"

mkdir -p "$output_dir"

cat <<EOF
Collection about to commence; expect a jumble of output as this is run in
parallel on all hosts. Results will be in $output_dir.
EOF
sleep 3;

for h in $hosts; do
    # Run in the background, so they all go in parallel
    # TODO `mktemp` works on Linux, but isn't terribly portable across various *nix
    ssh $h \
        'f=`mktemp`; /opt/membase/bin/mbcollect_info -v $f && cat $f && rm $f' \
        > "$output_dir/$h.zip" &
done

wait

echo " "
echo "Done - $output_dir:"
ls -lh "$output_dir"

# vim:set ft=sh sw=4 et ai:
